productpage:
  namespace: fuse-bookinfo-prd
  image: ghcr.io/fxselazy/bookinfo-productpage
  tag: prd
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 8080
  healthCheckPath: "/health"
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  host: bookinfo.hellodolphin.in.th
  path: "/fuse/productpage(/|$)(.*)"
  # host: bookinfo.opsta.net
  # path: "/student46/productpage(/|$)(.*)"
  serviceType: ClusterIP
extraEnv:
  DETAILS_HOSTNAME: http://fuse-details-prd:8082
  RATINGS_HOSTNAME: http://fuse-ratings-prd:8081
  REVIEWS_HOSTNAME: http://fuse-reviews-prd:9080