productpage:
  namespace: fuse-bookinfo-uat
  image: ghcr.io/fxselazy/bookinfo-productpage
  tag: uat
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 8080
  healthCheckPath: "/health"
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  host: bookinfo.uat.hellodolphin.in.th
  path: "/fuse/productpage(/|$)(.*)"
  # host: bookinfo.uat.opsta.net
  # path: "/student46/productpage(/|$)(.*)"
  serviceType: ClusterIP